### ISSUE TITLE
关于如何像 termux 一样可以管理存储文件

### ISSUE THREAD

**Issue by KateL2002** [PangBaiWork/WeBlog#1]
如上文，这个终端下不支持访问手机里的文件，且不能依靠 termux-setup-storage 指令来获取手机内部存储文件

**Comment by KateL2002** [comment]
再补充一点：这么做的目的，主要是为了可以方便利用 git 来来回推送，而且可以减少繁琐的操作

**Comment by PangBaiWork** [comment]
如果你在软件安装时授权储存权限，终端是可以访问sdcard文件的，cd /storage/emulated/0/即可

**Comment by PangBaiWork** [comment]
git来回推送可以利用侧边栏自定义脚本的功能，新建sh文件即可在运行时选择自定义脚本

**Comment by KateL2002** [comment]
那作者我能否给你写点 Get Started 这种文章吗？方便后来想用这个软件的😉

**Comment by KateL2002** [comment]
这个问题已经解决了，就是这个仓库内没有啥说明，不知道怎么找手机存储文件

**Comment by PangBaiWork** [comment]
进来坐坐 https://qm.qq.com/q/1wJcBUfst2
